name: "Vosk TTS"
slug: "vosk_tts"
version: "1.1.0"
description: "Local Wyoming-based Vosk TTS for Home Assistant with streaming"
startup: services
boot: auto
host_network: true
arch:
  - amd64
map:
  - config:rw
